"""
INJURY FEATURE FORMULAS - COMPLETE REFERENCE
============================================

All formulas extracted from feature_calculator_v5.py
"""

print('=' * 80)
print('INJURY FEATURE FORMULAS')
print('=' * 80)
print()

print('STEP 1: BASE INJURY IMPACT (PIE-WEIGHTED)')
print('-' * 80)
print()
print('For each injured player:')
print()
print('  base_impact = PIE * 20.0')
print('    (PIE = 0.15 → 3.0 point impact)')
print()
print('  z_score = (PIE - 0.0855) / 0.0230')
print('    (0.0855 = league avg, 0.0230 = std dev)')
print()
print('  gravity_multiplier = {')
print('    1.0                    if z_score < 1.0')
print('    1.0 + 0.15*(z-1)      if 1.0 <= z < 2.0  (good players)')
print('    1.15 + 0.35*(z-2)     if 2.0 <= z < 3.0  (stars)')
print('    1.50 * exp(0.25*(z-3)) if z >= 3.0       (superstars - exponential)')
print('  }')
print()
print('  player_impact = base_impact * gravity_multiplier')
print()
print('  team_injury_impact = sum(player_impact for all injured players with PIE >= 0.08)')
print()
print('Example: Anthony Davis (PIE = 0.185)')
print('  base = 0.185 * 20 = 3.7 points')
print('  z = (0.185 - 0.0855) / 0.023 = 4.33 (elite)')
print('  gravity = 1.50 * exp(0.25 * 1.33) = 2.06')
print('  impact = 3.7 * 2.06 = 7.62 points')
print()

print('STEP 2: EWMA BASELINE (10-GAME ROLLING AVERAGE)')
print('-' * 80)
print()
print('  ewma_injury_impact = EWMA(team_injury_impact, span=10)')
print()
print('  For each team, calculate rolling average of injury impacts over')
print('  last 10 games using exponential weighting (more recent = higher weight)')
print()
print('  Formula: EWMA_t = α * Impact_t + (1-α) * EWMA_{t-1}')
print('    where α = 2 / (span + 1) = 2/11 ≈ 0.182')
print()
print('Example: Lakers injury history')
print('  Games 1-5: No injuries → EWMA = 0.0')
print('  Game 6: AD out (7.6 impact) → EWMA = 0.182 * 7.6 + 0.818 * 0.0 = 1.38')
print('  Game 7: AD still out → EWMA = 0.182 * 7.6 + 0.818 * 1.38 = 2.51')
print('  Game 10: AD still out → EWMA = 6.5 (approaching 7.6)')
print()

print('FINAL FEATURES')
print('=' * 80)
print()

print('1. injury_impact_diff')
print('   = home_injury_impact - away_injury_impact')
print('   Interpretation: Positive = home disadvantaged')
print('   Importance: 6.0')
print()

print('2. injury_impact_abs')
print('   = abs(home_injury_impact) + abs(away_injury_impact)')
print('   Interpretation: Total injury burden (both teams)')
print('   Importance: 6.4')
print()

print('3. injury_shock_home')
print('   = home_injury_impact - home_ewma_injury_impact')
print('   Interpretation: Positive = worse injuries than usual (NEW bad news)')
print('   Importance: 6.7')
print()

print('4. injury_shock_away')
print('   = away_injury_impact - away_ewma_injury_impact')
print('   Interpretation: Positive = worse injuries than usual')
print('   Importance: 6.6')
print()

print('5. injury_shock_diff')
print('   = injury_shock_home - injury_shock_away')
print('   Interpretation: Positive = home has MORE unexpected injuries')
print('   Importance: 7.0 ★ HIGHEST')
print()

print('6. home_star_missing')
print('   = 1 if home_injury_impact >= 4.0 else 0')
print('   Interpretation: Binary flag for elite starter missing (~0.20 PIE)')
print('   Importance: 6.1')
print()

print('7. away_star_missing')
print('   = 1 if away_injury_impact >= 4.0 else 0')
print('   Interpretation: Binary flag for elite starter missing')
print('   Importance: 7.7 ★★ SECOND HIGHEST')
print()

print('8. star_mismatch')
print('   = home_star_missing - away_star_missing')
print('   Interpretation: {-1: away missing star, 0: symmetric, +1: home missing star}')
print('   Importance: 6.2')
print()

print('=' * 80)
print('IMPORTANCE RANKING')
print('=' * 80)
print()
print('1. away_star_missing      7.7  (Binary: Elite player out)')
print('2. injury_shock_diff      7.0  (Surprise injuries differential)')
print('3. injury_shock_home      6.7  (Home team surprise)')
print('4. injury_shock_away      6.6  (Away team surprise)')
print('5. injury_impact_abs      6.4  (Total injury load)')
print('6. star_mismatch          6.2  (Star advantage)')
print('7. home_star_missing      6.1  (Home elite out)')
print('8. injury_impact_diff     6.0  (Baseline differential)')
print()

print('=' * 80)
print('CURRENT STATUS IN MODELS')
print('=' * 80)
print()
print('43-feature model (xgboost_final_trial98_REFERENCE):')
print('  ✅ All 8 injury features included')
print()
print('19-feature model (model_v6_ml.xgb):')
print('  ✅ injury_impact_diff (baseline only)')
print('  ❌ Missing 7 shock/star features')
print()

print('=' * 80)
print('RECOMMENDATION FOR 20-FEATURE MODEL')
print('=' * 80)
print()
print('Add these 2 features to 19-feature model:')
print()
print('1. injury_shock_diff (7.0 importance)')
print('   - Captures "market-moving news" (new injuries)')
print('   - Already in feature_calculator_v5.py')
print()
print('2. away_star_missing (7.7 importance)')
print('   - Simple binary flag (PIE >= 4.0)')
print('   - Strong signal for road favorites')
print()
print('Result: 21-feature model with injury shock integration')
